### ISSUE TITLE
Желаемые фичи

### ISSUE THREAD

**Issue by mibamur** [rwpod/rwpod.github.io#1]
- [ ] Добавить вперед назад или след пред или просто стрелочки )))
- [ ] Добавить кнопки изменения скорости - такое есть в плеере ну или `document.getElementById('jp_audio_0').playbackRate=1.3;`
- [ ] сделать pls или m3u листы для сезонов

**Comment by alchapone** [comment]
@mibamur  "кнопки изменения скорости" это чтобы быстрее можно было нас прослушать? 😃

**Comment by mibamur** [comment]
это нормальная практика )
обычно youtube на ускорении смотрю/слушаю если это только не "йога" какой-нить
индийцев наоборот замедлять нужно :-)

**Comment by mibamur** [comment]
мож мигрируете на octopod?

**Comment by le0pard** [comment]
Сайт вообще предоставляет базовый функционал, для более "адванст" работы есть аудио плееры (в том числе с возможность подписки на RSS), где весь этот функционал будет работать эффективнее.

**Comment by le0pard** [comment]
> сделать pls или m3u листы для сезонов

У новостного подкаста сомнительная польза в прослушивание архивных записей (может даже быть проблема, что обсуждаемая ссылка уже может не работать)

**Comment by le0pard** [comment]
> мож мигрируете на octopod?

не понятно какая польза от этого.

**Comment by mibamur** [comment]
Алексей зарубил все предложения )
- с удовольствием слушаю все Ваши архивные выпуски, полезно знать историю некоторых событий/изменений в Ruby, а JS новости бывают не утрачивают свою актуальность и поныне
- так как архив довольно таки объемный былоб неплохо добавить возможность увеличить скорость imho
- октопод - поделился ссылкой )))

PS
спасибо огромное за подкаст
@le0pard - в последнее время начал делать video!? без комментариев, темы зачетные

**Comment by le0pard** [comment]
@mibamur я гляну, можно ли сделать xml по годам (можно сделать и весь, но его наверно будет тяжело скормить такой xml аудио софту). 

Лучше слушать с аудио софта, на сайте чисто для тех, кто не знает еще стоит слушать или нет (в нормальных можно и скорость выставлять). 

А octopod нам ничего не даст, потому что это jekyll с темой под поскасты, но что бы сделать аудио как у них по меткам - придется еще больше тратить времени на подготовку аудио файла.

**Comment by mibamur** [comment]
по поводу octopod согласен, но подход согласись там верный
для себя аудио могу и сам распарсить - не заморачивайтесь
со скоростью я конечно погоричился, удобнее слушать - как только начинается обсуждение темы открыть ссылку и самому вникать, но с комментариями )
