### ISSUE TITLE
предлагаемые темы, обзоры

### ISSUE THREAD

**Issue by mibamur** [rwpod/rwpod.github.io#2]
https://github.com/ageweke/fortitude
https://github.com/jarmo/require_all
https://github.com/jonathantribouharet/jt-rails-address

https://github.com/ruby-protobuf/protobuf
https://github.com/liveh2o/active_remote
https://github.com/apotonick/cells
https://github.com/apotonick/trailblazer

**Comment by le0pard** [comment]
Спасибо, часть уже была в предыдущих подкастах (тот же trailblazer).
