### ISSUE TITLE
New RWpod logo is broken in Firefox

### ISSUE THREAD

**Issue by EdwardDiehl** [rwpod/rwpod.github.io#3]
Open rwpod.com in firefox and check the logo.
My user agent string: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0`

**Comment by le0pard** [comment]
Thanks, fixed. Looks like https://github.com/svg/svgo "optimize" something in svg, which firefox cannot handle.
