### ISSUE TITLE
Middleman Favicons BUG Maker

### ISSUE THREAD

**Issue by xtsidx** [rwpod/rwpod.github.io#4]
Гем https://github.com/follmann/middleman-favicon-maker содержит баг
Вот даже есть открытая проблема почти по этому поводу https://github.com/follmann/middleman-favicon-maker/issues/42

Из за бага возникает артефакт, что в корне сайта RWPOD лежат "png иконки",
во первых которые исходя из настроек в config.rb впринципе там быть не должно,
а во вторых эти png на самом деле являются копиями оригинального SVG файла 
[1](http://www.rwpod.com/apple-icon-2048x2048.png), [2](http://www.rwpod.com/apple-touch-icon-152x152-precomposed.png), [3](http://www.rwpod.com/favicon.png) и тд

Сам столкнулся с этой проблемой при разработке pet-проекта, брал идеи реализации у rwpod

Исправление этой проблемы мне видится лишь, когда гем этот перепишут основательно, так как он не  верно смоделирован как расширение для middleman, насколько я могу судить.

Либо отказаться от этого гема и вручную наделать нужных иконок.

Либо написать своё расшерение для генерации favicons в sitemap приложения.

**Comment by le0pard** [comment]
@xtsidx на сколько я вижу - картинки доступны из правильных путей, в руте пусто:

http://www.rwpod.com/images/favicons/apple-touch-icon-144x144-precomposed.png - все отлично

http://www.rwpod.com/apple-touch-icon-144x144-precomposed.png - 404

**Comment by xtsidx** [comment]
Да доступны в /images/favicons, этого я и не отрицаю

Но в руте лежат лишние файлы

**Comment by le0pard** [comment]
@xtsidx fixed by https://github.com/rwpod/rwpod.github.io/commit/e0c48fd199426d66c901bdaeffdaabaf9c4ca2b6 Thanks.
