### ISSUE TITLE
Иконки соц. сетей перекрываются логотипом на мобильных устройствах

### ISSUE THREAD

**Issue by hetsketch** [rwpod/rwpod.github.io#5]
Собственно, вот пример
![image](https://user-images.githubusercontent.com/3451694/52622479-fd4d3100-2eba-11e9-8b6c-31d8415586fc.png)

Можно сделать отступ побольше или перенести куда-то в другое место

**Comment by le0pard** [comment]
Fixed by https://github.com/rwpod/rwpod.github.io/commit/7e557bc7b73d0e16002e9fcffdbb2705b98f45b0
